controller:
  podLabels:
    promtail: "true"
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      external-dns.alpha.kubernetes.io/hostname: management.joaquin.dev