azure:
  resourceGroup: dns
  tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
  subscriptionId: f22d63d0-6093-4a8f-83f3-7598e8fb6eb3
  useManagedIdentityExtension: true
provider: azure
txtOwnerId: "management"
domainFilters:
- kube101.dev

